table Apps
	lineageTag: 7f505845-383a-422d-b968-4602dacfc8d0

	column id
		dataType: string
		lineageTag: 29813b28-4609-414d-977b-580fb5dcb7ec
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: c8352cd1-2bc4-470a-8f57-40a3567bf250
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column lastUpdate
		dataType: string
		lineageTag: 2d71fe39-2975-4164-af9e-fe01634d8fb7
		summarizeBy: none
		sourceColumn: lastUpdate

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 9159acb1-4222-4af4-b923-f8218c3703dc
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column publishedBy
		dataType: string
		lineageTag: 2555033e-af15-473d-9e40-40edef0e4947
		summarizeBy: none
		sourceColumn: publishedBy

		annotation SummarizationSetBy = Automatic

	column workspaceId
		dataType: string
		lineageTag: 98fdc3a0-e14e-4121-975b-8bdb22411ca5
		summarizeBy: none
		sourceColumn: workspaceId

		annotation SummarizationSetBy = Automatic

	column URL
		dataType: string
		lineageTag: 5485182a-01d8-451a-9520-e0cfeb2943dd
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: URL

		annotation SummarizationSetBy = Automatic

	partition Apps-8473982c-d8d6-4971-a17d-ab3780263b9b = m
		mode: import
		queryGroup: PBIContent
		source = ```
				let
				    Apps = if is_valid() = "Forbidden" then #table({"id","name","lastUpdate","description","publishedBy","workspaceId","URL"}, {})
				    else
				    let
				        Query1 = Json.Document(Web.Contents("https://api.powerbi.com", 
				        [
				            RelativePath="v1.0/myorg/admin/apps",
				            Query = [
				                #"$top"= "999"
				            ],
				            Headers=[
				                Authorization=Text.Combine({"Bearer ", AccessToken()}, "")
				            ]
				        ])),
				        value = Query1[value],
				        #"Converted to Table" = Table.FromList(value, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				        #"Expanded Column1" = try Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"id", "name", "lastUpdate", "description", "publishedBy", "workspaceId", "users"}, {"id", "name", "lastUpdate", "description", "publishedBy", "workspaceId", "users"}) otherwise #table({"id", "name", "lastUpdate", "description", "publishedBy", "workspaceId", "users"},{}),
				        #"Removed Columns" = Table.RemoveColumns(#"Expanded Column1",{"users"}),
				        #"Added Custom" = Table.AddColumn(#"Removed Columns", "URL", each "https://app.powerbi.com/groups/me/apps/"&[id]),
				        #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"id", type text}, {"name", type text}, {"description", type text}, {"publishedBy", type text}, {"workspaceId", type text}, {"URL", type text}})
				    in
				        #"Changed Type"
				in
				    Apps
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

