table Capacities
	lineageTag: ba453a25-ca91-404c-83ca-82cae77cc150

	measure Capacities =
			
			CALCULATE(
			    DISTINCTCOUNT(Capacities[id])
			    , CROSSFILTER(Capacities[id], Workspaces[capacityId], BOTH)
			)
		formatString: 0
		lineageTag: 41e56391-24b5-430c-83b3-6e1a30d81e04

	column id
		dataType: string
		lineageTag: 5c4762a1-3a0f-48a1-8955-952ac7e4c33b
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column displayName
		dataType: string
		lineageTag: a51a5ee2-d61f-4449-9c81-d09f2fc5feaa
		summarizeBy: none
		sourceColumn: displayName

		annotation SummarizationSetBy = Automatic

	column admins
		dataType: string
		lineageTag: e267c79a-b51e-47f8-a36a-d71b96a5c509
		summarizeBy: none
		sourceColumn: admins

		annotation SummarizationSetBy = Automatic

	column sku
		dataType: string
		lineageTag: 850cfd5c-d585-4bbc-9b98-ed1e26b5c312
		summarizeBy: none
		sourceColumn: sku

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 575b561b-bae1-4749-ac68-d0b1832795b6
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column capacityUserAccessRight
		dataType: string
		lineageTag: 2919b9f8-16a9-4dd6-afe7-534d3a1a287b
		summarizeBy: none
		sourceColumn: capacityUserAccessRight

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 976a1e8a-f8d6-40b4-b354-8fb93aa99850
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column users
		dataType: string
		lineageTag: 63335890-f93a-4943-ad73-1a1e308ce230
		summarizeBy: none
		sourceColumn: users

		annotation SummarizationSetBy = Automatic

	partition Capacities-6c2246bf-9c2e-444e-a64b-733a0bb5872e = m
		mode: import
		queryGroup: PBIContent
		source = ```
				let
				    Capacities = if is_valid() = "Forbidden" then #table({"id","displayName","admins","sku","state","capacityUserAccessRight","region","users"}, {})
				else
				    let
				        Query1 = Json.Document(Web.Contents("https://api.powerbi.com", 
				        [
				            RelativePath="v1.0/myorg/admin/capacities",
				            Headers=[
				                Authorization=Text.Combine({"Bearer ", AccessToken()}, "")
				            ]
				        ])),
				        value = Query1[value],
				        #"Converted to Table" = Table.FromList(value, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				        #"Expanded Column1" = try Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"id", "displayName", "admins", "sku", "state", "capacityUserAccessRight", "region", "users"}, {"id", "displayName", "admins", "sku", "state", "capacityUserAccessRight", "region", "users"}) otherwise #table({"id", "displayName", "admins", "sku", "state", "capacityUserAccessRight", "region", "users"},{}),
				        #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"id", type text}, {"displayName", type text}, {"sku", type text}, {"state", type text}, {"capacityUserAccessRight", type text}, {"region", type text}})
				    in
				        #"Changed Type"
				in
				    Capacities
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

