table Dataflows
	lineageTag: 108d29b6-05f4-4d4c-80e4-dde644bd7928

	measure 'Dataflows Names' =
			
			CONCATENATEX(Dataflows, "- "&Dataflows[name], UNICHAR(10) )
		lineageTag: 96f79b6f-388e-41c0-919e-e4af7047123e

	column objectId
		dataType: string
		lineageTag: ad8e68e2-24d9-477a-b87b-bd5c9b5a37ab
		summarizeBy: none
		sourceColumn: objectId

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 1bc3858d-ad5f-4aa2-b7fa-9c42294dc96c
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: aa8b1260-53f4-4bbd-af6e-f643f79a6225
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column workspaceId
		dataType: string
		lineageTag: dd3cac2f-a698-4efc-b22f-f6d64ee01bc7
		summarizeBy: none
		sourceColumn: workspaceId

		annotation SummarizationSetBy = Automatic

	column modelUrl
		dataType: string
		lineageTag: d8227d33-6c17-4bff-ad12-2622fdef5850
		summarizeBy: none
		sourceColumn: modelUrl

		annotation SummarizationSetBy = Automatic

	column configuredBy
		dataType: string
		lineageTag: 4b862a39-db76-472e-bd87-9826c5b93e5e
		summarizeBy: none
		sourceColumn: configuredBy

		annotation SummarizationSetBy = Automatic

	column URL
		dataType: string
		lineageTag: 6207056d-c3e2-4840-8c69-b74544d33a11
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: URL

		annotation SummarizationSetBy = Automatic

	partition Dataflows-42ce867a-f380-4f2f-8386-c08683a08d37 = m
		mode: import
		queryGroup: PBIContent
		source = ```
				let
				    Dataflows = if is_valid() = "Forbidden" then #table({"objectId","name","description","workspaceId","modelUrl","configuredBy","URL"}, {})
				else
				    let    
				        Query1 = Json.Document(Web.Contents("https://api.powerbi.com", 
				        [
				            RelativePath="v1.0/myorg/admin/dataflows",
				            Headers=[
				                Authorization=Text.Combine({"Bearer ", AccessToken()}, "")
				            ]
				        ])),
				        value = Query1[value],
				        #"Converted to Table" = Table.FromList(value, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				        #"Expanded Column1" = try Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"objectId", "name", "description", "workspaceId", "modelUrl", "configuredBy", "users"}, {"objectId", "name", "description", "workspaceId", "modelUrl", "configuredBy", "users"}) otherwise #table({"objectId", "name", "description", "workspaceId", "modelUrl", "configuredBy", "users"},{}),
				        #"Removed Columns" = Table.RemoveColumns(#"Expanded Column1",{"users"}),
				        #"Added Custom" = Table.AddColumn(#"Removed Columns", "URL", each "https://app.powerbi.com/groups/"&[workspaceId]&"/dataflows/"&[objectId]),
				        #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"objectId", type text}, {"name", type text}, {"description", type text}, {"workspaceId", type text}, {"modelUrl", type text}, {"configuredBy", type text}, {"URL", type text}})
				    in
				        #"Changed Type"
				in
				    Dataflows
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

