table Reports
	lineageTag: fdeba4c1-a439-499a-bd97-48ed102d4fd3

	measure 'Reports Names' =
			
			CONCATENATEX(Reports, "- "&Reports[name], UNICHAR(10) )
		lineageTag: 95d6f8a5-7361-4446-987d-95bad1c90af3

	column workspaceId
		dataType: string
		lineageTag: 827cffca-433d-4c90-96ee-e435f41ac028
		summarizeBy: none
		sourceColumn: workspaceId

		annotation SummarizationSetBy = Automatic

	column id
		dataType: string
		lineageTag: a7019341-9ae5-4847-a625-a064f1280396
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column reportType
		dataType: string
		lineageTag: 535aa60c-2226-46b0-a199-761067c76f75
		summarizeBy: none
		sourceColumn: reportType

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 19c3c96f-8bf1-441c-9c63-5f0f894fde21
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column datasetId
		dataType: string
		lineageTag: 5983faad-ea05-48c2-bff1-dace4ea3b5a7
		summarizeBy: none
		sourceColumn: datasetId

		annotation SummarizationSetBy = Automatic

	column users
		dataType: string
		lineageTag: de24c814-8000-485e-9559-e80ec38e8d19
		summarizeBy: none
		sourceColumn: users

		annotation SummarizationSetBy = Automatic

	column subscriptions
		dataType: string
		lineageTag: eb481600-bc20-43cd-82ff-831b182419e2
		summarizeBy: none
		sourceColumn: subscriptions

		annotation SummarizationSetBy = Automatic

	column modifiedDateTime
		dataType: string
		lineageTag: 7588ce14-9a1a-48b1-8968-d1758efbe2fe
		summarizeBy: none
		sourceColumn: modifiedDateTime

		annotation SummarizationSetBy = Automatic

	column createdDateTime
		dataType: string
		lineageTag: 99126e93-88fc-4ecf-b040-524de822af79
		summarizeBy: none
		sourceColumn: createdDateTime

		annotation SummarizationSetBy = Automatic

	column appId
		dataType: string
		lineageTag: c648b9c0-f590-41af-98e8-abdb9656e9c9
		summarizeBy: none
		sourceColumn: appId

		annotation SummarizationSetBy = Automatic

	column URL
		dataType: string
		lineageTag: be05138b-9c6b-49b6-b669-e2c8e1ac0944
		dataCategory: WebUrl
		summarizeBy: none
		sourceColumn: URL

		annotation SummarizationSetBy = Automatic

	column isItAppReport
		dataType: string
		lineageTag: eb21e4fd-4391-4f90-bbfc-a5411746b3c3
		summarizeBy: none
		sourceColumn: isItAppReport

		annotation SummarizationSetBy = Automatic

	partition Reports-e2618dbe-f56d-40af-91a5-42e52c892ecb = m
		mode: import
		queryGroup: PBIContent
		source = ```
				let
				    Reports = if is_valid() = "Forbidden" then #table({"workspaceId","id","reportType","name","datasetId","users","subscriptions","modifiedDateTime","createdDateTime","appId","URL","isItAppReport"}, {})
				else
				    let
				        Query1 = Json.Document(Web.Contents("https://api.powerbi.com", 
				        [
				            RelativePath="v1.0/myorg/admin/groups",
				            Query = [
				                #"$top"= "999",
				                #"$expand"="reports"
				            ],
				            Headers=[
				                Authorization=Text.Combine({"Bearer ", AccessToken()}, "")
				            ]
				        ])),
				        value = Query1[value],
				        #"Converted to Table" = Table.FromList(value, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				        #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"id", "reports"}, {"workspaceId", "reports"}),
				        #"Expanded reports" = Table.ExpandListColumn(#"Expanded Column1", "reports"),
				        #"Expanded reports1" = Table.ExpandRecordColumn(#"Expanded reports", "reports", {"id", "reportType", "name", "datasetId", "users", "subscriptions", "modifiedDateTime", "createdDateTime", "appId"}, {"id", "reportType", "name", "datasetId", "users", "subscriptions", "modifiedDateTime", "createdDateTime", "appId"}),
				        #"Filtered Rows" = Table.SelectRows(#"Expanded reports1", each ([id] <> null)),
				        #"Added Custom" = Table.AddColumn(#"Filtered Rows", "URL", each "https://app.powerbi.com/groups/"&[workspaceId]&"/reports/"&[id]),
				        #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"id", type text}, {"reportType", type text}, {"name", type text}, {"datasetId", type text}, {"modifiedDateTime", type text}, {"createdDateTime", type text}, {"appId", type text}, {"workspaceId", type text}, {"URL", type text}}),
				        #"Added Custom1" = Table.AddColumn(#"Changed Type", "isItAppReport", each if Text.Contains([name], "[App]") then "App_Report" else "No App Report")
				    in
				        #"Added Custom1"
				in
				    Reports
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

