name: SimplePBI-Ops-Deploy-Dev

on:
  push:
    branches:
      - dev
    paths:
      - 'Workspaces/**'  # Trigger only when there's a change in this folder

jobs:
  SimplePBI-Ops-Dev-Deploy:
    runs-on: ubuntu-latest
    
    # Set your prefiex target for environment workspace. If your folder name is Workspace Sales and the dev environment workspace is Workspace Sales - Dev, write " - Dev" value for the variable
    env:
      DEPLOY_ENV: "_Dev"
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v6
        with:
         fetch-depth: 3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      # Step 3: Install the necessary Python package from PyPI
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install simplepbi 

      # Step 4: Get list of changed folders ending with .report or .semanticmodel
      - name: Get changed folders
        id: detect_changes
        run: |
            target_folder="Workspaces/"

            changed_folders=$(git diff --name-only "${{ github.event.before }}" "${{ github.sha }}" -- "$target_folder" | \
              grep -vE '\.pbip$' | \
              grep -oE '^.*\.(SemanticModel|Report|Dataset)' | \
              sort -u)

            existing_folders=""
            while IFS= read -r folder; do
              if [ -d "$folder" ]; then
                existing_folders+="$folder"$'\n'
              fi
            done <<< "$changed_folders"

            existing_folders=$(echo "$existing_folders" | sed '/^\s*$/d' | paste -sd "," -)

            echo "changed_folders=$existing_folders" >> $GITHUB_ENV
            echo "Changed folders: $existing_folders"

      # Step 5: Run the Python script with the list of changed folders and secret key
      - name: Run Python script
        run: python ldw-deploy.py "ldw-key" "${DEPLOY_ENV}" ${{ secrets.TENANT_ID }} ${{ secrets.APP_ID }} ${{ secrets.SECRET_KEY }} ${{ env.changed_folders }} 
