name: SimplePBI-Ops-Deploy

on:
  push:
    branches:
      - dev
    paths:
      - 'Workspaces/**'  # Trigger only when there's a change in this folder

jobs:
  SimplePBI-Ops-Dev-Deploy:
    runs-on: ubuntu-latest
    
    # Set your prefiex target for environment workspace. If your folder name is Workspace Sales and the dev environment workspace is Workspace Sales - Dev, write " - Dev" value for the variable
    env:
      DEPLOY_ENV: "_Dev"

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v6
        with:
         fetch-depth: 3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 3: Install the necessary Python package from PyPI
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install simplepbi 

      # Step 4: Get list of changed folders ending with .report or .semanticmodel
      - name: Get changed folders
        id: detect_changes
        run: |
          target_folder="Workspaces/"

          # 1. Get changed files
          # 2. Filter for specific Power BI project folders
          # 3. Use sed to capture everything up to the supported extensions and discard the rest
          # 4. Sort and Uniq handles the "show folder once" requirement
          changed_folders=$(git diff --name-only HEAD^..HEAD -- "$target_folder" | \
            grep -iE '\.(Report|SemanticModel|Dataset)/' | \
            sed -E 's|^(.*?\.(Report|SemanticModel|Dataset)).*|\1|' | \
            sort | uniq)

          # Filter only existing folders to handle deletions gracefully
          existing_folders=""
          while IFS= read -r folder; do
            if [ -d "$folder" ]; then
              [ -n "$existing_folders" ] && existing_folders+=","
              existing_folders+="$folder"
            fi
          done <<< "$changed_folders"

          echo "changed_folders=$existing_folders" >> $GITHUB_ENV
          echo "Filtered folders: $existing_folders"

      # Step 5: Run the Python script with the list of changed folders and secret key
      - name: Run Python script
        run: python ldw-deploy.py "ldw-key" "${DEPLOY_ENV}" ${{ secrets.TENANT_ID }} ${{ secrets.APP_ID }} ${{ secrets.SECRET_KEY }} ${{ env.changed_folders }} 
