name: Process Reports and Models

on:
  push:
    branches:
      - main
    paths:
      - 'Workspaces/**'  # Trigger only when there's a change in this folder

jobs:
  process_changes:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
         fetch-depth: 3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install the necessary Python package from PyPI
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install simplepbi 

      # Step 4: Get list of changed folders ending with .report or .semanticmodel
      - name: Get changed folders
        id: detect_changes
        run: |
            target_folder="Workspaces/"
            keyword_pattern=".Report|.SemanticModel|.Dataset"

            # Get list of changed files under Workspaces/
            changed_files=$(git diff --name-only HEAD^..HEAD -- "$target_folder")

            matched_folders=""

            while IFS= read -r file; do
              # Check if path contains one of the target keywords
              if echo "$file" | grep -qE "$keyword_pattern"; then
                # Make sure the file still exists (i.e., not deleted)
                if [[ -f "$file" ]]; then
                  folder=$(dirname "$file")
                  matched_folders+="$folder"$'\n'
                fi
              fi
            done <<< "$changed_files"

            # Deduplicate and convert to comma-separated string
            changed_folders=$(echo "$matched_folders" | sort -u | tr '\n' ',' | sed 's/,$//')

            echo "changed_folders=$changed_folders" >> $GITHUB_ENV
            echo "Changed folders: $changed_folders"

      # Step 5: Run the Python script with the list of changed folders and secret key
      - name: Run Python script
        run: python ldw-deploy.py "ldw-key" ${{ secrets.TENANT_ID }} ${{ secrets.APP_ID }} ${{ secrets.SECRET_KEY }} ${{ env.changed_folders }} 

