name: Process Reports and Models

on:
  push:
    branches:
      - main
    paths:
      - 'Workspaces/**'  # Trigger only when there's a change in this folder

jobs:
  process_changes:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
         fetch-depth: 3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install the necessary Python package from PyPI
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install simplepbi 

      # Step 4: Get list of changed folders ending with .report or .semanticmodel
      - name: Get changed folders
        id: detect_changes
        run: |
    target_folder="Workspaces/"

    # Get list of parent directories of changed files under target_folder
    changed_folders=$(git diff --name-only HEAD^..HEAD -- "$target_folder" | \
      sed 's|/[^/]*$||' | sort | uniq)

    # Filter only existing folders (exclude deleted ones)
    existing_folders=""
    for folder in $changed_folders; do
      if [ -d "$folder" ]; then
        existing_folders+="$folder,"
      fi
    done

    # Remove trailing comma
    existing_folders="${existing_folders%,}"

    echo "changed_folders=$existing_folders" >> $GITHUB_ENV
    echo "Changed folders: $existing_folders"
      # Step 5: Run the Python script with the list of changed folders and secret key
      - name: Run Python script
        run: python ldw-deploy.py "ldw-key" ${{ secrets.TENANT_ID }} ${{ secrets.APP_ID }} ${{ secrets.SECRET_KEY }} ${{ env.changed_folders }} 

