name: PowerBi-CICD-SimplePBI

on:
  push:
    branches:
      - main
    paths:
      - 'Workspaces/**'  

jobs:
  SimplePBI-Ops-Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: CallSimplePBI-Ops
        uses: ladataweb/SimplePBI-Ops@v0.0.1

        with:
          custom-text: "Hi, running the SimplePBI Ops process..."
        env:
          TENANT_ID : ${{ secrets.TENANT_ID  }}
          APP_ID : ${{ secrets.APP_ID  }}
          SECRET_KEY : ${{ secrets.SECRET_KEY  }}